image: node:10.16.0

pipelines:
  branches:
    live:
      - step:
          name: build
          caches:
            - node
          script:
            - npm install
            - npm run build:prod
            - apt-get update
            - apt-get install --yes zip
            - ls
            - cd ./dist/point-cloud-rendering/
            - ls
            - zip -r app.zip .
            - ls
            - curl -X POST -u "$DEPLOYMENT_USER:$DEPLOYMENT_PW" -T "app.zip" $DEPLOYMENT_URL
