image: node:10.16.0

pipelines:
  branches:
    live:
      - step:
          name: Build & Deploy
          caches:
            - node
          script:
            - apt-get update
            - apt-get install --yes zip
            - cd web-surfels-ui
            - npm install
            - npm run build
            - cd ./dist/point-cloud-rendering/
            - zip -r app.zip .
            - curl -X POST -u "$DEPLOYMENT_USER:$DEPLOYMENT_PW" -T "app.zip" $DEPLOYMENT_URL
